#cloud-config
autoinstall:
  version: 1

  identity:
    hostname: elgentos-ubuntu-p14s
    username: elgentos
    password: "$6$06Ot4bgyw5j3L8Dn$N8o2btGghAI0KynX4Mab7krf.9Z/mtAyWrftK26d8Z8zSLzxgxuqwm7ArRXrV6iwMTWwF4GUS3ZfdEvA/YWIl0"  # elgentos123

  shutdown: poweroff

  timezone: Europe/Amsterdam

  keyboard:
    layout: us

  drivers:
    install: true

  ssh:
    install-server: true
    allow-pw: true
    
  storage:
    layout:
      name: lvm
      password: pleasechangemeasap

  interactive-sections:
    - network
    - identity

  packages:
    - build-essential
    - composer
    - dnsutils
    - docker-compose
    - docker.io
    - firefox
    - fonts-powerline
    - gimp
    - git
    - gpg
    - gnome-shell-extensions
    - htop
    - httrack
    - jq
    - lsb-release
    - multitail
    - ncdu
    - silversearcher-ag
    - tig
    - traceroute
    - ubuntu-desktop
    - ufw
    - vim
    - vlc
    - wget
    - xclip
    - zsh

  snaps:
    - name: chromium
    - name: discord
    - name: firefox
    - name: gcolor3
    - name: postman
    - name: spotify
    - name: sqlitebrowser
    - name: steam
    - name: slack

  late-commands:
    # Resize 100GB partition to full space available
    - curtin in-target -- lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv
    - curtin in-target -- resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
  
    # Install Brave
    - curtin in-target -- wget -qO- https://dl.brave.com/install.sh | sh
  
    # Installing Warp
    - curtin in-target -- /bin/bash -c "wget --content-disposition -O /tmp/warp.deb 'https://app.warp.dev/download?package=deb' && dpkg -i /tmp/warp.deb"

    # Raise inotify watches limit
    - curtin in-target -- sh -c 'echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf'
    - curtin in-target -- sh -c 'echo "fs.inotify.max_user_instances=512" >> /etc/sysctl.conf'
    - curtin in-target -- sh -c 'sysctl -p'
  
    # Installing 1password-cli
    - curtin in-target -- wget -O /tmp/1password.asc https://downloads.1password.com/linux/keys/1password.asc
    - curtin in-target -- gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg /tmp/1password.asc
    - curtin in-target -- echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" | tee /etc/apt/sources.list.d/1password.list
    - curtin in-target -- mkdir -p /etc/debsig/policies/AC2D62742012EA22/
    - curtin in-target -- wget -O /etc/debsig/policies/AC2D62742012EA22/1password.pol https://downloads.1password.com/linux/debian/debsig/1password.pol
    - curtin in-target -- mkdir -p /usr/share/debsig/keyrings/AC2D62742012EA22
    - curtin in-target -- wget -O /tmp/debsig.gpg https://downloads.1password.com/linux/keys/1password.asc
    - curtin in-target -- gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg /tmp/debsig.gpg
    - curtin in-target -- apt update
    - curtin in-target -- apt install -y 1password 1password-cli
  
    # Install oh-my-zsh
    - curtin in-target -- sh -c "$(wget -qO- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  
    # Install nvm
    - curtin in-target -- wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

    # Installing Gnome extensions
    #- curtin in-target -- gnome-extensions enable clipboard-indicator@tudmotu.com
    #- curtin in-target -- gnome-extensions enable caffeine@patapon.info
    #- curtin in-target -- gnome-extensions enable donotdisturbwhilecall@janlaping.de
