name: docker-make vim

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    strategy:
      matrix:
        version: ['20.04']
    runs-on: ubuntu-${{ matrix.version }}
    name: Ubuntu ${{ matrix.version }}
    env:
      TTY: 0
    steps:
      - uses: actions/checkout@v2
      - name: Test docker-make with VIM
        run: ./docker-make vim
