name: Install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    strategy:
      matrix:
        version:
          - '20.04'
    runs-on: ubuntu-${{ matrix.version }}
    name: Ubuntu ${{ matrix.version }}
    env:
      TTY: 0
      INTERACTIVE: 0
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Copy SSH key
        if: ${{ env.ACT }}
        run: |
          mkdir -p ~/.ssh
          cp -f .ssh/* ~/.ssh
      - name: Setup SSH key
        if: ${{ !env.ACT }}
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: unnecessary
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install all software
        run: |
          ./install all

          # Verify installation.
          for optional in $(grep -nR 'optional:: |' | cut -d'|' -f2- | sort -u); \
            do echo "VERIFY $optional"; \
            bash -c 'make -q "$optional"'; \
          done
