name: Install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install:
    strategy:
      matrix:
        version:
          - '20.04'
    runs-on: ubuntu-${{ matrix.version }}
    name: Ubuntu ${{ matrix.version }}
    env:
      TTY: 0
      INTERACTIVE: 0
      DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        if: ${{ env.ACT }}
        run: |
          apt update -y
          apt install nodejs -y
      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          known_hosts: unnecessary
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Remove Node
        if: ${{ env.ACT }}
        run: apt remove nodejs -y
      - name: Install all software
        run: ./install all
