name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Ubuntu 20.04
    steps:
      - uses: actions/checkout@v2
      - name: Update APT repositories
        run: apt update -y
      - name: Install required software
        run: make install INTERACTIVE=0
      - name: Install optional software
        run: make optional INTERACTIVE=0
      - name: Upgrade APT packages
        run: apt upgrade -y
      - name: Clean up
        run: apt autoremove -y