name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test install target
    steps:
      - uses: actions/checkout@v2
      - name: make install
        run: make install INTERACTIVE=0
      - name: make optional
        run: make optional INTERACTIVE=0