name: make slack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ubuntu:
    strategy:
      matrix:
        version: ['20.04']
    runs-on: ubuntu-${{ matrix.version }}
    name: Ubuntu ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Update APT repositories
        run: sudo apt update -y
      - name: Install Slack
        run: make slack INTERACTIVE=0
