name: Install Transmission Remote

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    strategy:
      matrix:
        version: ['20.04']
    runs-on: ubuntu-${{ matrix.version }}
    name: Ubuntu ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Update APT repositories
        run: sudo apt update -y
      - name: Install optional software
        run: make transmission-remote INTERACTIVE=0
      - name: Upgrade APT packages
        run: sudo apt upgrade -y
      - name: Clean up
        run: sudo apt autoremove -y
